name: grid_pad
description: GridPad Flutter layout
version: 0.0.9
repository: https://github.com/touchlane/gridpad_flutter

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.21.4

flutter: