name: grid_pad
description: GridPad Flutter layout
version: 1.0.0
repository: https://github.com/touchlane/gridpad_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: ^1.21.4

flutter: