name: Publishing

on:
  push:
    branches: [ "master" ]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write
    uses: touchlane/gridpad_flutter/.github/workflows/publishing_to_pub.yml@v1
